Repository web3-storage/web3.storage, pull requests merged in 2022-02, with the labels that each got.

#947 Feature #563: Schema updates for admin site.
  packages/db/postgres/tables.sql
Labels: topic/tg, topic/admin

#955 Adding user_tag table to facilitate user restricted application features.
  packages/db/postgres/tables.sql
Labels: topic/admin

#992 Move GATEWAY to env and expose ipfs gateway
  packages/api/.env.local.tpl
  packages/api/src/car.js
  packages/api/src/constants.js
  packages/api/src/env.js
  packages/api/test/cors.spec.js
  packages/api/test/scripts/worker-globals.js
  packages/api/wrangler.toml
  packages/tools/docker/cluster/docker-compose.yml
Labels: kind/enhancement, topic/devexp, topic/pot
