Repository web3-storage/web3.storage, pull requests merged in 2022-08, with the labels that each got.

#1752 chore: correct w3name staging and prod urls in cron job.
  packages/cron/src/jobs/names.js
Labels: pi/w3name

#1686 chore: remove /name API endpoints and storage
  packages/api/src/env.js
  packages/api/src/index.js
  packages/api/src/name.js
  packages/api/src/utils/ipns/index.js
  packages/api/src/utils/ipns/pb/ipns.js
  packages/api/test/auth.spec.js
  packages/api/test/name.spec.js
  packages/api/test/scripts/helpers.js
  packages/api/wrangler.toml
  packages/client/package.json
  packages/db/index.js
Labels: topic/pot, pi/w3name

#1786 chore: switch to org-level GH secret for Cloudflare token
  .github/workflows/api.yml
  .github/workflows/website.yml
Labels: topic/pot
