Repository web3-storage/web3.storage, pull requests merged in 2022-06, with the labels that each got.

#1006 feat: DB schema and API for user_tag_proposal.
  packages/db/postgres/migrations/012-user_tag_proposal.sql
  packages/db/postgres/tables.sql
Labels: topic/admin, stack/admin-storage

#1333 feat: cases for visual minimums to both stored and pinned meters
  packages/website/components/account/storageManager/storageManager.js
Labels: stack/website

#1455 feat!: switch to Elastic IPFS
  .env.tpl
  package-lock.json
  packages/api/package.json
  packages/api/src/car.js
  packages/api/src/env.js
  packages/api/src/utils/logs.js
  packages/api/test/car.spec.js
  packages/api/test/hooks.js
  packages/api/test/mocks/backup/put_bucket#raw#@root_cid#@user_id#@hash.js
  packages/api/test/mocks/cluster/post_pins#@cid.js
  packages/api/test/mocks/package.json
  packages/api/test/scripts/constants.js
  packages/api/test/scripts/worker-globals.js
  packages/tools/docker/minio/docker-compose.yml
  packages/tools/package.json
  packages/tools/scripts/cli.js
  packages/tools/scripts/minio.js
  packages/tools/scripts/util.js
Labels: pi/SLA
